#!/usr/bin/env bash
#Bash script for displaying numbers 1 to 100 while changing numbers to certain phrases if they are
#multiples of 3 an/or 5.
i=1
while [ $i -le 100 ]
do
    if (( $i % 3 && 5 ))
    then echo "FizzBuzz"
	 if (( $i % 3 ))
	 then echo "Fizz"
	      if (( $i % 5 ))
	      then echo "Buzz"
	      else echo "$i"
		   ((i++))
fi
done
