#!/usr/bin/env bash
#Bash script for displaying numbers 1 to 100 while changing numbers to certain phrases if they are
#multiples of 3 an/or 5.
for i in {1..100}
do
    if (( i % 3 == 0 && 5 == 0 ))
    then echo "FizzBuzz"
	 elif (( i % 3 == 0 ))
	 then echo "Fizz"
	      elif (( i % 5 == 0 ))
	      then echo "Buzz"
    else echo "$i"
	 
fi
done
