#!/usr/bin/env bash
#Bash script that will display the contents of a file
#while displaying only username,user id, and home directory path
while read -r passwd; do
echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
