#!/usr/bin/env bash
#Printing Best School 10 times while on the 9th displays Hi on a new line

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 8 ]
       then printf "Best School\nHi\n"
    else
	echo "Best School"
       fi
	 ((count++))
	 done
