#!/usr/bin/env bash
#Printing Best School 10 times while on the 9th displays Hi on a new line
count=0
while [ $count -lt 10 ]
do
    echo "Best School"
    (( $count++ ))
while [ $count= 9 ]
do
    echo "Hi"
done
