#!/usr/bin/env bash
#Creating a clock representation

i=0
while [ $i -le 12 ]
do
    echo "Hour: $Hour"
    minute=1
    while [ $minute -le 59 ]
    do echo "$minute"
       (( minute++ ))
       done
       (( hour++ ))
		  done
