#!/usr/bin/env bash
#Creating a clock representation

i=0
while [ $i -le 12 ]
do
    echo "Hour: $i"    
minute=1
    while [ $minute -le 59 ]
    do
	echo "$minute"
        (( i++ ))
	(( minute++ ))
        done
done
